const TEMAS = {

  "🍞👨‍🍳 Profissões": [
    "Médico 🩺","Professor 🍎","Bombeiro 🚒","Engenheiro 🏗️","Advogado ⚖️",
    "Policial 👮","Enfermeiro 💉","Dentista 😬","Cozinheiro 👨‍🍳","Piloto ✈️",
    "Arquiteto 🏛️","Veterinário 🐶","Jornalista 📰","Programador 💻","Designer 🎨",
    "Psicólogo 🧠","Agricultor 🌾","Eletricista ⚡","Mecânico 🔧","Carpinteiro 🪚",
    "Padeiro 🥖","Garçom 🍽️","Cabeleireiro 💇","Fotógrafo 📸","Artista 🎭",
    "Músico 🎵","Ator 🎬","Cantor 🎤","Escritor ✍️","Economista 💰",
    "Contador 🧮","Administrador 📊","Vendedor 💼","Jogador de Futebol ⚽","Nutricionista 🥗",
    "Fisioterapeuta 💪","Biólogo 🔬","Astronauta 🚀","Pesquisador 🔍","Motorista 🚗",
    "Corretor 🏠","Segurança 🛡️","Juiz ⚖️","DJ 🎧","Youtuber 📹","Influencer 🌟","Tatuador 🖋️","Barbeiro ✂️","Costureiro 🧵","Marinheiro ⚓","Soldado 🪖","Meteorologista 🌦️","Oceanógrafo 🌊","Chef de Cozinha 👨‍🍳","Maquiador 💄", "Piloto de Drones 🛸","Cientista de Dados 📈","Analista de Sistemas 🖥️","Tradutor 🌐","Terapeuta 👐",
    "Babá 👶","Cuidador de Idosos 👵","Zelador 🧹","Porteiro 🛎️","Recepcionista 🧾", "Bibliotecário 📖","Instrutor de Yoga 🧘","Coach 🌟","Motoboy 🛵","Pescador 🎣", "Guia Turístico 🌍","Cerimonialista 🎊","Estilista 👠","Piloto de Helicóptero 🚁","Paramédico 🚑",
    "Radialista 📻","Operador de Caixa 💳","Serralheiro 🛠️","Técnico em Informática 🧰","Pedreiro 🧱", "Pintor 🎨","Marceneiro 🪑","Sapateiro 👞","Lavador de Carros 🧽","Fiscal de Loja 🧾"
  ],

  "🔑 Objetos": [
    "Clipes de papel 🖇️","Grampeador 📎","Borracha 🧽","Régua 📏","Apontador ✏️","Envelope ✉️","Etiqueta 🏷️","Calculadora 🧮","Projetor 📽️","Tela de projeção 🖥️",
    "Capacete ⛑️","Escada 🪜","Trena 📏","Fita adesiva 🧷","Cadeira de rodas ♿",
    "Carrinho de compras 🛒","Carrinho de bebê 👶","Tapete 🪵","Almofada 🛏️","Cobertor 🛌",
    "Travesseiro 💤","Guarda-roupa 🚪","Abajur 🛋️","Fogareiro 🏕️","Barraca ⛺",
    "Cooler 🧊","Drone 🚁","Bússola 🧭","Cantil 🥤","Moeda 🪙",
    "Carteira 👛","Bolsa 👜","Mala de viagem 🧳","Rádio 📻","Televisão 📺",
    "Controle remoto 🎛️","Disco de vinil 💿","Pen drive 💾","Carregador 🔌","Bateria 🔋",
    "Joystick 🎮","Lápis ✏️","Cadeira 🪑","Mesa 🏠","Celular 📱",
    "Bola ⚽","Chave 🔑","Relógio ⌚","Livro 📖","Computador 💻",
    "Tesoura ✂️","Caneta 🖊️","Caderno 📓","Óculos 👓","Garfo 🍴",
    "Faca 🔪","Colher 🥄","Prato 🍽️","Copo 🥤","Garrafa 🍼",
    "Panela 🍳","Ventilador 💨","Lâmpada 💡","Espelho 🪞","Escova de dentes 🪥",
    "Vassoura 🧹","Aspirador 🌀","Máquina de lavar 🧺","Ferro de passar 👔","Fone de ouvido 🎧",
    "Teclado ⌨️","Mouse 🖱️","Impressora 🖨️","Webcam 📹","Mochila 🎒",
    "Guarda-chuva ☔","Lanterna 🔦","Martelo 🔨","Chave de fenda 🛠️","Pincel 🖌️",
    "Violão 🎸","Piano 🎹","Dado 🎲","Bicicleta 🚲","Skate 🛹",
    "Raquete 🎾","Troféu 🏆","Câmera 📷","Extintor 🧯","Fogão 🍳",
    "Geladeira ❄️","Micro-ondas 🍲","Batedeira 🥣","Balde 🪣","Mangueira 🌿",
    "Regador 🌼","Enxada ⚒️","Vaso de planta 🪴","Luminária 💡","Garrafa térmica 🧃"
  ],

  "🗺️🧭 Países": [
    "Brasil 🇧🇷","Estados Unidos 🇺🇸","Canadá 🇨🇦","México 🇲🇽","Argentina 🇦🇷",
    "França 🇫🇷","Espanha 🇪🇸","Itália 🇮🇹","Alemanha 🇩🇪","Portugal 🇵🇹",
    "Reino Unido 🇬🇧","Japão 🇯🇵","China 🇨🇳","Coreia do Sul 🇰🇷","Índia 🇮🇳",
    "Rússia 🇷🇺","Austrália 🇦🇺","Nova Zelândia 🇳🇿","África do Sul 🇿🇦","Egito 🇪🇬",
    "Grécia 🇬🇷","Turquia 🇹🇷","Tailândia 🇹🇭","Vietnã 🇻🇳","Indonésia 🇮🇩",
    "Chile 🇨🇱","Colômbia 🇨🇴","Peru 🇵🇪","Costa Rica 🇨🇷","Cuba 🇨🇺",
    "Uruguai 🇺🇾","Paraguai 🇵🇾","Bolívia 🇧🇴","Venezuela 🇻🇪","Panamá 🇵🇦",
    "Jamaica 🇯🇲","Haiti 🇭🇹","Noruega 🇳🇴","Suécia 🇸🇪","Finlândia 🇫🇮",
    "Dinamarca 🇩🇰","Islândia 🇮🇸","Irlanda 🇮🇪","Suíça 🇨🇭","Áustria 🇦🇹",
    "Bélgica 🇧🇪","Países Baixos 🇳🇱","Polônia 🇵🇱","Hungria 🇭🇺","Romênia 🇷🇴",
    "Croácia 🇭🇷","Ucrânia 🇺🇦","Cazaquistão 🇰🇿","Irã 🇮🇷","Arábia Saudita 🇸🇦",
    "Emirados Árabes Unidos 🇦🇪","Israel 🇮🇱","Paquistão 🇵🇰","Bangladesh 🇧🇩","Malásia 🇲🇾",
    "Singapura 🇸🇬","Filipinas 🇵🇭","Camboja 🇰🇭","Nepal 🇳🇵","Marrocos 🇲🇦",
    "Nigéria 🇳🇬","Quênia 🇰🇪","Etiópia 🇪🇹","Angola 🇦🇴","Moçambique 🇲🇿"
  ],
  
  "🎬📽️ Filmes Famosos": [
    "O Poderoso Chefão 🎩",
    "Titanic 🚢",
    "Jurassic Park 🦖",
    "Star Wars ⚔️",
    "Harry Potter ⚡",
    "De Volta para o Futuro ⏳",
    "O Rei Leão 🦁",
    "Avatar 🔵",
    "Vingadores 🦸",
    "Homem-Aranha 🕷️",
    "Batman 🦇",
    "Matrix 💊",
    "Forrest Gump 🏃",
    "Clube da Luta 👊",
    "Interestelar 🚀",
    "Gladiador 🗡️",
    "Pulp Fiction 🍔",
    "Cidade de Deus ✝️",
    "Tropa de Elite 🔫",
    "O Auto da Compadecida 😇",
    "Coringa 🃏",
    "Frozen ❄️",
    "Toy Story 🤠",
    "Shrek 🧅",
    "Os Incríveis 🦸‍♀️",
    "Procurando Nemo 🐠",
    "Up - Altas Aventuras 🎈",
    "Divertida Mente 🧠",
    "Ratatouille 👨‍🍳",
    "Wall-E 🤖",
    "O Lobo de Wall Street 💼",
    "Bohemian Rhapsody 🎤",
    "La La Land 🎶",
    "Whiplash 🥁",
    "O Pianista 🎹",
    "A Lista de Schindler 🕊️",
    "O Resgate do Soldado Ryan 🎖️",
    "Dunkirk ⚓",
    "Os Miseráveis 🎭",
    "Encanto 🦋",
    "Viva - A Vida é uma Festa 💀",
    "Moana 🌊",
    "Zootopia 🐰🦊",
    "Corra! 🏃‍♂️",
    "Parasita 🪳🏠",
    "Oldboy 🥢🔨",
    "Roma 🇲🇽",
    "Moonlight 🌙",
    "A Origem 🌀",
    "Duna 🌵",
    "Barbie 💖",
    "Oppenheimer ☢️",
    "Mad Max: Estrada da Fúria 🚗🔥",
    "Indiana Jones 🏺",
    "O Grande Gatsby 🎉",
    "Psicose 🚿",
    "Django Livre 🔫🤠",
    "Deadpool 🔫😈",
    "Logan 🐺",
    "Guardiões da Galáxia 🚀🎶",
    "Piratas do Caribe ☠️",
    "O Hobbit 🧙",
    "O Senhor dos Anéis 💍",
    "A Forma da Água 🐠",
    "Blade Runner 🤖",
    "Aniquilação 🌺",
    "Coraline 👧",
    "A Chegada 🛸",
    "O Grande Hotel Budapeste 🏨",
    "Tudo em Todo Lugar 🌌",
    "Escola de Rock 🎸",
    "Pequena Miss Sunshine 👑",
    "Rocky 🥊",
    "Creed 🥊🔥",
    "Trainspotting 💊",
    "O Show de Truman 📺",
    "Her ❤️🤖",
    "500 Dias com Ela 💔",
    "A Vida é Bela 🌻",
    "Amélie Poulain 🇫🇷",
    "Central do Brasil ✉️",
    "Bacurau 🌵",
    "Minha Mãe é uma Peça 👩‍🦱",
    "Carandiru 🏢",
    "Lisbela e o Prisioneiro 🍿",
    "Dona Flor e Seus Dois Maridos 🍳",
    "O Homem que Copiava 💵",
    "2 Filhos de Francisco 🎸",
    "Estômago 🍲",
    "Abril Despedaçado 🌾",
    "Madame Satã 💃",
    "O Que é Isso, Companheiro? 🇧🇷",
    "Tropa de Elite 2 🛡️",
    "Cazuza - O Tempo Não Para 🎤",
    "Bicho de Sete Cabeças 🏥",
    "O Menino e o Mundo 🎨",
    "Jaws (Tubarão) 🦈",
    "E.T. - O Extraterrestre 👽",
    "O Iluminado 🪓",
    "O Silêncio dos Inocentes 🦋",
    "O Exorcista ✝️",
    "Alien, o Oitavo Passageiro 👾",
    "Top Gun ✈️",
    "Missão Impossível 💣",
    "John Wick 🔫🐶",
    "Pânico 🔪😱",
    "Mamma Mia! 💃",
    "O Diabo Veste Prada 👠",
    "Legalmente Loira 💅",
    "Meninas Malvadas 💖",
    "As Branquelas 👱‍♀️",
    "Se Beber, Não Case! 🥂",
    "Velozes e Furiosos 🏎️",
    "Beleza Americana 🌹",
    "O Menino do Pijama Listrado 🚂",
    "12 Anos de Escravidão ⛓️",
    "Cidadão Kane 📰",
    "Casablanca 🍸",
    "Ben-Hur 🐎",
    "E o Vento Levou 💨",
    "Psicopata Americano 🔪",
    "Kill Bill ⚔️",
    "Seven: Os Sete Crimes Capitais 📦",
    "Coração Valente ⚔️🛡️",
    "Beetlejuice 👻",
    "Singin' in the Rain ☔",
    "Grease - Nos Tempos da Brilhantina 🕺"
  ],

  "🦧🐩 Animais": [
    "Cachorro 🐶","Gato 🐱","Leão 🦁","Tigre 🐯","Elefante 🐘",
    "Girafa 🦒","Macaco 🐒","Cavalo 🐴","Vaca 🐮","Galinha 🐔",
    "Pato 🦆","Águia 🦅","Tubarão 🦈","Golfinho 🐬","Panda 🐼",
    "Coala 🐨","Zebra 🦓","Rinoceronte 🦏","Hipopótamo 🦛","Crocodilo 🐊",
    "Cobra 🐍","Borboleta 🦋","Abelha 🐝","Formiga 🐜","Aranha 🕷️",
    "Caranguejo 🦀","Polvo 🐙","Estrela-do-mar ⭐","Pinguim 🐧","Coruja 🦉",
    "Papagaio 🦜","Tucano 🐦","Beija-flor 🌸","Camelo 🐫","Esquilo 🐿️",
    "Raposa 🦊","Lobo 🐺","Urso 🐻","Tamanduá 🐜",
    "Tatu 🦔","Capivara 🦫","Bicho-preguiça 🦥","Canguru 🦘","Ornitorrinco 🦫",
    "Morcego 🦇","Lêmure 🐒","Foca 🦭","Narval 🐋","Baleia 🐳",
    "Orca 🐋","Peixe-palhaço 🐠","Camarão 🦐","Lagosta 🦞","Cavalo-marinho 🐴",
    "Pavão 🦚","Ganso 🪿","Guepardo 🐆","Onça-pintada 🐆","Hamster 🐹",
    "Camaleão 🦎","Sapo 🐸","Tartaruga 🐢","Caracol 🐌","Porco-espinho 🦔",
    "Gambá 🦨","Alce 🦌","Rena 🦌","Texugo 🦡","Lontra 🦦",
    "Medusa 🪼","Enguia 🐍","Arraia 🦈","Avestruz 🐣","Flamingo 🦩"
  ],

  "🐈‍⬛ Lendas Famosas": [
    "Saci-Pererê 🧢","Curupira 🔥","Iara 🧜‍♀️","Boto-Cor-de-Rosa 🐬","Mula Sem Cabeça 🐴",
    "Lobisomem 🌕","Vampiro 🧛","Frankenstein 👹","Zumbi 🧟","Pé Grande 🦶",
    "Monstro do Lago Ness 🏴󠁧󠁢󠁳󠁣󠁴󠁿","Chupacabra 🐐","Fênix 🔥","Dragão 🐉","Unicórnio 🦄",
    "Medusa 🐍","Sereia 🧜‍♀️","Kraken 🦑","Fantasma 👻","Bruxa 🧙‍♀️",
    "Boitatá 🔥","Caipora 🏹","Troll 🧌","Gárgula 🗿","Minotauro 🐂",
    "Quimera 🐐🦁🐍","Esfinge 🦁👩","Cerbero 🐶🔥","Centauro 🐎👨","Sátiro 🐐👨",
    "Grifo 🦅🦁","Pegaso 🐎","Aranha gigante 🕷️","Tifão 🌪️","Harpias 🦅👩",
    "Gênio da Lâmpada 🧞‍♂️","Duende 🧙‍♂️","Werewolf 🐺🌕","Drácula 🦇","Múmia ⚰️",
    "Alien 👽","El Coco 😱","La Llorona 😭","Slender Man 🎩","Anubis 🐺⚰️"
  ],

  "🙏✨ Gírias Baianas": [
    "Oxente! 😲","Arretado! 🤩","Vixe Maria! 🙏","Firmeza! ✊","Mermão! 🤜🤛",
    "Tá ligado? 🤔","Coisa fina! 👌","Vambora! 🚶‍♂️","Tá amarrado! 🙅","Barril! 🍻",
    "Chocado! 🤯","Baratino! 🤥","Tá zero bala! 🆕","Axé! ✨","Pão de sal! 🥖",
    "Comer água! 🍻","Aondeee! 😲","Brocar! 💥","Que saco! 😩","Me passei! 😅",
    "Maresia! 😴","Zuada! 🔊","Zum-zum-zum! 🗣️","Tô na larica! 🍔","Fazer o corre! 🏃",
    "Se pique! 🏃‍♂️","Tô de gastação! 😜","Laranjada! 🍊","Se saia! 🚫","Romper o ano! 🎉",
    "Não sou baú! 🗣️","Tem uma cara! ⏳","Bora! 🚀","Rpz 😎","Massa! 👍",
    "Tá doidão? 🤪","Mainha! 👩","Paleta! 🚶‍♂️","Viu! ✔️","Pronto! ✅",
    "Digaí!? 👀","Pipocou! 💥","Na tora! 💪","Eu tô em água! 🍺","Cabrunco! 🤬",
    "Dijunto! 💀","Azuado! 🤪","Sua cara nem arde! 😳","Lá ele! 🙈","Sarava! 🙌"
  ],

  // ===== NOVOS TEMAS =====

 "🎵🎤 Músicas Famosas": [
    "Bohemian Rhapsody - Queen 🎸",
    "Thriller - Michael Jackson 🕺",
    "Hey Jude - Beatles 🎺",
    "Billie Jean - Michael Jackson 🕴️",
    "Hotel California - Eagles 🏨",
    "Imagine - John Lennon 🕊️",
    "Like a Rolling Stone - Bob Dylan 🎸",
    "Purple Rain - Prince 🟣",
    "Stairway to Heaven - Led Zeppelin 🪜",
    "Born to Run - Springsteen 🏃",
    "Wonderwall - Oasis 🧱",
    "Shape of You - Ed Sheeran 💪",
    "Despacito - Luis Fonsi 🌴",
    "Gangnam Style - PSY 🐴",
    "Uptown Funk - Bruno Mars 🕺",
    "Happy - Pharrell Williams 😊",
    "Aquarela do Brasil 🇧🇷",
    "Asa Branca - Luiz Gonzaga 🐦",
    "Garota de Ipanema 🌊",
    "País Tropical - Jorge Ben 🌴",
    "Evidências - Chitãozinho e Xororó 💔",
    "Triste, Louca ou Má - Francisco El Hombre 🎸",
    "Coração de Estudante - Milton Nascimento 🎓",
    "Maria - Pixinguinha 🪗",
    "Que País é Esse - Legião Urbana 🇧🇷",
    "Eduardo e Mônica - Legião Urbana 💌",
    "Faroeste Caboclo - Legião Urbana 🤠",
    "Pais e Filhos - Legião Urbana 👨‍👦",
    "Tempo Perdido - Legião Urbana ⌛",
    "Baby - Os Mutantes 🍼",
    "Só Você - Sandy e Junior 💕",
    "Quando a Chuva Passar - Ivete Sangalo 🌧️",
    "Vai Malandra - Anitta 💃",
    "Então Vai - Claudinho e Buchecha 🕺",
    "Rap do Solitário - Rappin Hood 🎙️",
    "Vida Loka - Racionais MC's 🏙️",
    "Sorry - Justin Bieber 😔",
    "Baby Shark 🦈",
    "Let It Go - Frozen ❄️",
    "We Will Rock You - Queen 🤜",
    "Eye of the Tiger - Survivor 🐯",
    "Don't Stop Believin' - Journey 🚀",
    "Sweet Child O' Mine - Guns N' Roses 🌹",
    "Under the Bridge - RHCP 🌉",
    "Losing My Religion - R.E.M. 🙏",
    "Yesterday - Beatles 🎻",
    "Smells Like Teen Spirit - Nirvana 🎸",
    "Dancing Queen - ABBA 💃",
    "Stayin' Alive - Bee Gees 🕺",
    "I Will Always Love You - Whitney Houston ✨",
    "Maluco Beleza - Raul Seixas 🕶️",
    "O Descobridor dos Sete Mares - Tim Maia 🌊",
    "Anna Julia - Los Hermanos 🌻",
    "Anunciação - Alceu Valença 🔔",
    "Exagerado - Cazuza 🌹",
    "Take On Me - a-ha ✍️",
    "Livin' on a Prayer - Bon Jovi 🙌",
    "Back in Black - AC/DC ⚡",
    "Rolling in the Deep - Adele 🎤",
    "Single Ladies - Beyoncé 💍",
    "Vou Deixar - Skank 🎧",
    "Lanterna dos Afogados - Paralamas do Sucesso 🔦",
    "Primeiros Erros - Capital Inicial 🔄",
    "Velha Infância - Tribalistas 🎈",
    "Blinding Lights - The Weeknd 🕶️",
    "Sweet Dreams - Eurythmics 🍬",
    "Every Breath You Take - The Police 🕵️",
    "Girls Just Want to Have Fun - Cyndi Lauper 🎀",
    "One - U2 ☝️",
    "Hips Don't Lie - Shakira 💃",
    "With or Without You - U2 🎸",
    "Rebel Rebel - David Bowie ⚡",
    "O Segundo Sol - Cássia Eller ☀️",
    "Mulher de Fases - Raimundos 🌙",
    "Metamorfose Ambulante - Raul Seixas 🦎",
    "Toda Forma de Amor - Lulu Santos 🏳️‍🌈",
    "Onde Você Mora - Cidade Negra 🏠",
    "Pela Estante - Pitty 📚",
    "Proibida Pra Mim - Charlie Brown Jr. 🛹",
    "Tempos Modernos - Lulu Santos ⏳",
    "Fio Maravilha - Jorge Ben Jor ⚽",
    "Mas Que Nada - Sergio Mendes 🎹",
    "Chega de Saudade - João Gilberto 🎸",
    "O Bebado e a Equilibrista - Elis Regina 🎪",
    "Como Nossos Pais - Elis Regina 👪",
    "Apenas um Rapaz Latino-Americano - Belchior 🌵",
    "Roda Viva - Chico Buarque 🎡",
    "Cálice - Chico Buarque e Milton Nascimento 🍷",
    "Ideologia - Cazuza 🧠",
    "Codinome Beija-Flor - Cazuza 🐦",
    "O Tempo Não Para - Cazuza ⏱️",
    "Vira-Vira - Mamonas Assassinas 🍖",
    "Pelados em Santos - Mamonas Assassinas 🚗",
    "Camila, Camila - Nenhum de Nós 👩",
    "Inútil - Ultraje a Rigor 🚫",
    "Zé do Caroço - Leci Brandão 🎙️",
    "Trem das Onze - Adoniran Barbosa 🚂",
    "O Show Tem Que Continuar - Fundo de Quintal 🎭",
    "Pode Chorar - Jorge & Mateus 😢",
    "Ai Se Eu Te Pego - Michel Teló 🖐️",
    "Show das Poderosas - Anitta 👑",
    "Burguesinha - Seu Jorge 💅",
    "We Are the Champions - Queen 🏆",
    "Bad Guy - Billie Eilish 😈",
    "Waka Waka - Shakira ⚽",
    "Perfect - Ed Sheeran 💍",
    "Macarena - Los Del Río 💃",
    "Faraó Divindade do Egito - Olodum 🏺",
    "Prefixo de Verão - Banda Mel ☀️",
    "Baianidade Nagô - Banda Mel 🥁",
    "Dandalunda - Margareth Menezes 🦁",
    "Mila - Netinho ⛵",
    "Araketu é Bom Demais - Araketu 🥁",
    "O Canto da Cidade - Daniela Mercury 🏙️",
    "Maimbê Dandá - Daniela Mercury 🐚",
    "Dalila - Ivete Sangalo 🏜️",
    "Sorte Grande - Ivete Sangalo 🏗️",
    "Eva - Banda Eva 🚀",
    "Beleza Rara - Banda Eva ✨",
    "Chandeirô - Carlinhos Brown 🥥",
    "Amor I Love You - Marisa Monte ❤️",
    "Naquela Mesa - Nelson Gonçalves 🍽️",
    "Infiel - Marília Mendonça 💔",
    "Largado às Traças - Zé Neto & Cristiano 🍺",
    "Não Quero Dinheiro - Tim Maia 💰",
    "Taj Mahal - Jorge Ben Jor 🕌"
  ],

  "📺🍿 Séries e Novelas": [
    "Breaking Bad 🧪",
    "Game of Thrones 🐉",
    "Stranger Things 🔮",
    "The Office 💼",
    "Friends 🛋️",
    "The Crown 👑",
    "House of Cards 🃏",
    "Black Mirror 📱",
    "The Mandalorian ⚔️",
    "Squid Game 🦑",
    "La Casa de Papel 💰",
    "Narcos 🟤",
    "Dark 🌀",
    "Peaky Blinders 🎩",
    "Sherlock 🔍",
    "Grey's Anatomy 🩺",
    "Lost 🏝️",
    "Prison Break 🔓",
    "How I Met Your Mother 🍺",
    "The Big Bang Theory 🔭",
    "The Walking Dead 🧟",
    "Westworld 🤖",
    "Chernobyl ☢️",
    "Mindhunter 🧠",
    "Money Heist 🔴",
    "Ozark 💵",
    "Euphoria 💊",
    "Succession 🏢",
    "Ted Lasso ⚽",
    "The Bear 🍳",
    "White Lotus 🌺",
    "Severance 🏢",
    "The Last of Us 🍄",
    "House of the Dragon 🐉",
    "Andor 🚀",
    "Wednesday 🖤",
    "Schitt's Creek 🌲",
    "Brooklyn Nine-Nine 👮",
    "Parks and Recreation 🌳",
    "Arrested Development 🍌",
    "Avenida Brasil 🇧🇷",
    "Amor de Mãe 👩‍👦",
    "O Clone 🧬",
    "Senhora do Destino ✋",
    "Malhação 🏫",
    "Chiquititas 🎀",
    "Rebelde 🎸",
    "Carrossel 🎠",
    "Balacobaco 😂",
    "A Grande Família 👨‍👩‍👧‍👦",
    "Chaves 🔑",
    "Chapolin Colorado 💪",
    "The Boys 🦸‍♂️",
    "Better Call Saul ⚖️",
    "The Sopranos 🔫",
    "Mad Men 🥃",
    "Sex Education 🍆",
    "Bridgerton 🐝",
    "Vikings 🪓",
    "Cobra Kai 🐍",
    "The Witcher 🐺",
    "Fleabag 🦊",
    "Twin Peaks 🦉",
    "The Handmaid's Tale 📕",
    "The Umbrella Academy ☂️",
    "Suits 👔",
    "Elite 🏫",
    "Renascer 🍫",
    "O Rei do Gado 🐄",
    "Roque Santeiro ⛪",
    "Tieta 🐐",
    "Pantanal 🐆",
    "Vale Tudo 🍷",
    "Caminho das Índias 🕌",
    "Verdades Secretas 👠",
    "Mulheres de Areia 🏖️",
    "Da Cor do Pecado 🏝️",
    "Cheias de Charme 🎤",
    "Cordel Encantado 🏰",
    "Ó Paí, Ó 🎶",
    "Cine Holliúdy 🎥",
    "Sob Pressão 🏥",
    "Cidade Invisível 👣",
    "3% 🏜️",
    "Tapas & Beijos 💋",
    "Sai de Baixo 🏢",
    "Os Normais 🛋️",
    "Toma Lá, Dá Cá 🏘️",
    "Sítio do Picapau Amarelo 🌽",
    "Marimar 🐚",
    "Maria do Bairro 🧹",
    "A Usurpadora 🎭"
  ],
  
  "🍕🍔 Comidas e Bebidas": [
    "Pizza 🍕",
    "Hambúrguer 🍔",
    "Sushi 🍣",
    "Tapioca 🫓",
    "Coxinha 🍗",
    "Pão de Queijo 🧀",
    "Feijoada 🫘",
    "Churrasco 🥩",
    "Caipirinha 🍋",
    "Açaí 🫐",
    "Brigadeiro 🍫",
    "Beijinho 🥥",
    "Quindim 🌟",
    "Pastel 🫔",
    "Bolinho de Bacalhau 🐟",
    "Acarajé 🫘",
    "Moqueca 🍲",
    "Vatapá 🟡",
    "Bobó de Camarão 🦐",
    "Tacacá 🍜",
    "Baião de Dois 🫘",
    "Pato no Tucupi 🦆",
    "Caldo de Cana 🍹",
    "Guaraná 🟤",
    "Mate 🧉",
    "Sorvete 🍦",
    "Waffle 🧇",
    "Panqueca 🥞",
    "Crepe 🥞",
    "Macarrão 🍝",
    "Risoto 🍚",
    "Lasanha 🫕",
    "Strogonoff 🍛",
    "Picanha 🥩",
    "Frango Assado 🍗",
    "Costela 🦴",
    "Rabada 🐄",
    "Dobradinha 🤢",
    "Sarapatel 🍲",
    "Mocotó 🦴",
    "Pamonha 🌽",
    "Curau 🌽",
    "Canjica 🍚",
    "Pé de Moleque 🥜",
    "Cocada 🥥",
    "Romeu e Julieta 🧀🍬",
    "Doce de Leite 🥛",
    "Goiabada 🍐",
    "Marmelada 🟠",
    "Pudim 🍮",
    "Mousse de Maracujá 🟡",
    "Petit Gâteau 🍫",
    "Cheesecake 🍰",
    "Tiramisù ☕",
    "Crème Brûlée 🔥",
    "Chocolate Quente ☕",
    "Café Coado ☕",
    "Espresso ☕",
    "Latte 🥛",
    "Vitamina 🥤",
    "Açaí com Granola 🫐",
    "Pitaya 🐉",
    "Cupuaçu 🟤",
    "Pequi 🌴",
    "Cajá 🟡",
    "Maracujá 🟡",
    "Graviola 🌿",
    "Buriti 🌴",
    "Taperebá 🌳",
    "Bacaba 🌴",
    "Carne do Sol ☀️",
    "Esfiha 🥟",
    "Quibe 🍘",
    "Taco 🌮",
    "Nacho 🧀",
    "Paella 🥘",
    "Hot Dog 🌭",
    "Batata Frita 🍟",
    "Kebab 🥙",
    "Hummus 🫘",
    "Falafel 🧆",
    "Empada 🥧",
    "Quiche 🥧",
    "Bacalhoada 🐟",
    "Escondidinho 🥔",
    "Arroz Carreteiro 🐎",
    "Feijão Tropeiro 🤠",
    "Moqueca Baiana 🥘",
    "Caruru 🥦",
    "Abará 🥥",
    "Bolinha de Queijo 🧀",
    "Enroladinho de Salsicha 🌭",
    "Pão com Linguiça 🥖",
    "Queijo Coalho 🍢",
    "Cerveja 🍺",
    "Vinho 🍷",
    "Suco de Laranja 🍊",
    "Água de Coco 🥥",
    "Refrigerante 🥤",
    "Cuscuz Nordestino 🌽",
    "Bolo de Rolo 🌀",
    "Sonho 🍩",
    "Churros 🥖",
    "Donut 🍩",
    "Muffin 🧁",
    "Brownie 🟫",
    "Salada de Frutas 🥣",
    "Gelatina 🍮",
    "Paçoca 🥜",
    "Bolo de Cenoura 🥕",
    "Bolo de Fubá 🍞",
    "Pão Francês 🥖",
    "Croissant 🥐",
    "Bagrete 🥖",
    "X-Tudo 🍔",
    "Farofa 🍚"
  ],
  
  "🏆🥇 Esportes e Atletas": [
    "Futebol ⚽","Vôlei 🏐","Basquete 🏀","Tênis 🎾","Natação 🏊",
    "Atletismo 🏃","Ginástica Artística 🤸","Judô 🥋","Boxe 🥊","Surf 🏄",
    "Fórmula 1 🏎️","Ciclismo 🚴","Esqui ⛷️","Patinação ⛸️","Hipismo 🐎",
    "Golf ⛳","Rugby 🏉","Handebol 🤾","Polo Aquático 🏊","Remo 🚣",
    "Pelé ⚽👑","Ronaldo Fenômeno 🇧🇷","Ronaldinho Gaúcho 🎩","Neymar 🇧🇷","Messi",
    "Cristiano Ronaldo 🇵🇹","Mbappé ⚡","Haaland 🎯","Vini Jr 🇧🇷","Endrick 🌟",
    "Ayrton Senna 🏎️","Michael Schumacher 🏎️","Lewis Hamilton 🏆","Max Verstappen 🔵","Fernando Alonso ⭐",
    "Serena Williams 🎾","Roger Federer 🎾","Rafael Nadal 🌟","Djokovic 🎾","Carlos Alcaraz 🌹",
    "Usain Bolt ⚡","Michael Phelps 🏊","Simone Biles 🤸","Muhammad Ali 🥊","Mike Tyson 🥊",
    "LeBron James 🏀","Michael Jordan 🐐","Kobe Bryant 🐍","Stephen Curry 🎯","Giannis 🦌",
    "Rebeca Andrade 🇧🇷🤸","Daiane dos Santos 🇧🇷","César Cielo 🇧🇷🏊","Gustavo Borges 🇧🇷","Fofão 🇧🇷🏐",
    "Magnus Carlsen ♟️","Tiger Woods ⛳","Lance Armstrong 🚴","Eddy Merckx 🚴","Valentino Rossi 🏍️"
  ],

  "🌐💻 Tecnologia e Apps": [
    "Instagram 📸","WhatsApp 💬","TikTok 🎵","YouTube ▶️","Google 🔍",
    "Facebook 👍","Twitter/X 🐦","Snapchat 👻","Pinterest 📌","LinkedIn 💼",
    "Netflix 🎬","Spotify 🎵","Amazon 📦","Uber 🚗","iFood 🍕",
    "Nubank 💜","PicPay 💳","Mercado Livre 🛒","OLX 🏷️","Airbnb 🏠",
    "iPhone 📱","Android 🤖","Windows 🪟","MacOS 🍎","Linux 🐧",
    "Inteligência Artificial 🤖","ChatGPT 💬","Bitcoin ₿","Blockchain ⛓️","NFT 🖼️",
    "Metaverso 🌐","Realidade Virtual 👓","Realidade Aumentada 🔮","Cloud Computing ☁️","Big Data 📊",
    "5G 📶","Wi-Fi 📶","Bluetooth 🔵","GPS 🗺️","QR Code 📱",
    "Impressora 3D 🖨️","Drones 🚁","Carro Autônomo 🚗","Tesla ⚡","SpaceX 🚀",
    "Robô Aspirador 🤖","Smart TV 📺","Alexa 🔊","Siri 🍎","Google Assistente 🔍",
    "Streaming 📺","Podcast 🎙️","E-commerce 🛍️","Startup 🚀","Hackathon 💻",
    "App Store 📱","Play Store 🤖","GitHub 🐙","Stack Overflow 💻","Wikipedia 📚"
  ]
};
